baseURL: "https://ha-cindy.github.io/" 
title: Cindy Ha
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: about/
          weight: 5 
        - name: CV
          url: cv/
          weight: 2
        - name: Research
          url: research/
          weight: 3
        - name: Teaching 
          url: teaching/
          weight: 3
        - name: Art
          url: art/
          weight: 4 

params:
    description: "I am a research specialist in the Department of Psychology at Princeton University."
    author: Cindy Ha
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Cindy Ha
          subtitle: "Hi there! I am a research specialist / lab manager at Princeton University, working with Dr. Anuj Shah and Dr. Betsy Levy Paluck.
          <br>  <br> I graduated from Northwestern University with a double major in Data Science and Psychology in 2024."
          imageUrl: "headshot.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about/
            - name: CV
              url: cv/
            - name: Research
              url: research/
            - name: Teaching 
              url: teaching/
            - name: Art
              url: art/

    socialIcons:
        - name: Email
          url: mailto:cindyha@princeton.edu
        - name: GitHub
          url: https://github.com/ha-cindy
        - name: LinkedIn
          url: https://www.linkedin.com/in/hacindy02/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Cindy Ha"
      icon: /favicon-miffy.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2