baseURL: "https://ha-cindy.github.io/" 
title: Cindy Ha
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: about
          url: about/
          weight: 2
        - name: cv
          url: /cv.pdf
          weight: 2
          target: "_blank"
        - name: research
          url: research/
          weight: 3
        - name: art
          url: art/
          weight: 4 

params:
    description: "I am a research specialist in the Department of Psychology at Princeton University."
    author: Cindy Ha
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Cindy Ha
          imageUrl: "headshot.png"
          imageWidth: 140
          imageHeight: 140
          buttons:
            - name: about
              url: about/
            - name: cv
              url: cv/
            - name: research
              url: research/
            - name: art 
              url: art/

    socialIcons:
        - name: Email
          url: mailto:cindyha@princeton.edu
        - name: Bluesky
          url: https://bsky.app/profile/hacindy.bsky.social
        - name: GitHub
          url: https://github.com/ha-cindy
        - name: Orcid
          url: https://orcid.org/0009-0008-0757-7028 
        - name: LinkedIn
          url: https://www.linkedin.com/in/hacindy02/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Cindy Ha"
      icon: /favicon-cat.png
      iconHeight: 19

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2